name: Build and Deploy

on:
  push:
    branches:
      - main  # Change this to your default branch if different
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Full history for jekyll-last-modified-at

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7'
          bundler-cache: true # This caches dependencies

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Jekyll dependencies
        run: bundle install

      - name: Build Jekyll site
        run: JEKYLL_ENV=production bundle exec jekyll build
        env:
          JEKYLL_ENV: production

      - name: Install npm dependencies
        run: npm ci || npm install

      - name: Install Mintlify CLI
        run: npm install -g mintlify@latest

      - name: Build Mintlify documentation
        run: |
          mkdir -p ./_site/docs
          cp -r ./docs/* ./_site/docs/

      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          cname: mgks.dev # If you have a custom domain 